subscribers:

  camera_reading:
    topic: /webcam/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

  compiled_message:
    topic: /detection/compiled_ros_msg
    queue_size: 1000
    latch: false

image_view:

  enable_opencv: true
  use_darknet: false
  wait_key_delay: 2
  enable_console_output: false
